version: "3.7"

services:
  nginx:
    build:
      context: ./
    ports:
      - 8080:8080
      # proxied to vouch - now integrated as a subpath of 8080
      # - 9090:9090
    # restart: always
    networks:
      - web
    volumes:
      - ./nginx-config/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx-config/upstreamLocal.conf:/var/nginxconf/upstream.conf:ro
      - ./public:/var/www/html:ro
    depends_on:
      - "vouch_proxy"

  vouch-proxy:
    image: quay.io/vouch/vouch-proxy:alpine-latest
    environment:
      # These variables will be populated using the host environmental variables,
      # so make sure to set those or edit this file
      - OAUTH_CLIENT_ID
      - OAUTH_CLIENT_SECRET
      - OAUTH_PROVIDER
      - OAUTH_CODE_CHALLENGE_METHOD
      - OAUTH_AUTH_URL
      - OAUTH_TOKEN_URL
      - OAUTH_USER_INFO_URL
      - OAUTH_END_SESSION_ENDPOINT
      - OAUTH_SCOPES
      - OAUTH_CALLBACK_URL
      - VOUCH_COOKIE_DOMAIN
      - VOUCH_TESTING
      - VOUCH_ALLOWALLUSERS
      - VOUCH_COOKIE_SECURE
      - VOUCH_PORT
    networks:
      - web

networks:
  web:
    driver: bridge
