apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - sso-secrets.yaml
patchesStrategicMerge:
  - vouchDeployment.yaml

configMapGenerator:
  - name: upstream-{{APP_NAME}}-{{ENVIRONMENT}}
    files:
      - upstream=./nginx/upstream.conf