apiVersion: v1
kind: Secret
metadata:
  name: sso-secrets
stringData:
  OAUTH_CLIENT_ID: <your_client_id>
  OAUTH_CLIENT_SECRET: <your_client_secret>
  OAUTH_PROVIDER: oidc
  OAUTH_CODE_CHALLENGE_METHOD: S256
  OAUTH_AUTH_URL: https://dev-<your_id>.okta.com/oauth2/default/v1/authorize
  OAUTH_TOKEN_URL: https://dev-<your_id>.okta.com/oauth2/default/v1/token
  OAUTH_USER_INFO_URL: https://dev-<your_id>.okta.com/oauth2/default/v1/userinfo
  OAUTH_END_SESSION_ENDPOINT: https://dev-<your_id>.okta.com/oauth2/default/v1/logout
  OAUTH_SCOPES: openid,email,profile
  OAUTH_CALLBACK_URL: http://localhost:8080/auth
  VOUCH_COOKIE_DOMAIN: localhost
  VOUCH_TESTING: 'false'
  VOUCH_ALLOWALLUSERS: 'true'
  VOUCH_COOKIE_SECURE: 'false'
  VOUCH_PORT: '9090'